// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function BulletPoints(props) {
  return JsxRuntime.jsx("ul", {
              children: Belt_Array.map(props.points, (function (point) {
                      return JsxRuntime.jsx("li", {
                                  children: JsxRuntime.jsx("p", {
                                        children: point
                                      })
                                }, point);
                    }))
            });
}

var make = BulletPoints;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
