// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function CloseIcon(props) {
  return JsxRuntime.jsx("svg", {
              children: JsxRuntime.jsxs("g", {
                    children: [
                      JsxRuntime.jsx("path", {
                            id: "Vector",
                            d: "M15.625 4.375L4.375 15.625",
                            stroke: "black",
                            strokeLinecap: "round",
                            strokeLinejoin: "round",
                            strokeWidth: "1.5"
                          }),
                      JsxRuntime.jsx("path", {
                            id: "Vector_2",
                            d: "M15.625 15.625L4.375 4.375",
                            stroke: "black",
                            strokeLinecap: "round",
                            strokeLinejoin: "round",
                            strokeWidth: "1.5"
                          })
                    ],
                    id: "X"
                  }),
              height: "20",
              width: "20",
              fill: "none",
              viewBox: "0 0 20 20",
              xmlns: "http://www.w3.org/2000/svg"
            });
}

var make = CloseIcon;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
