// Generated by ReScript, PLEASE EDIT WITH CARE


var newList = [
  {
    mainHeader: "Booking Details and Modifications",
    subList: [
      {
        subHeader: "Quotation and Changes",
        pointList: [
          {
            point: "The provided quotation is based on the details provided by the customer, including the movement date, pickup and drop location.",
            subPointList: []
          },
          {
            point: "If there are any deviations in the movement date, or pickup and drop location revising the distance a revised quotation will be offered based on the changes.",
            subPointList: []
          },
          {
            point: "For any issues with respect to the revised quotation, the customer is expected to contact Porter customer care directly at 022 4410 4444 / 022 6268 4444.",
            subPointList: []
          }
        ]
      },
      {
        subHeader: "Cancellation",
        pointList: [
          {
            point: "Free cancellation is allowed up to 1 hour before the scheduled time slot",
            subPointList: [
              "test",
              "test2"
            ]
          },
          {
            point: "If the cancellation is made after this timeframe, a cancellation fee will be charged.",
            subPointList: []
          }
        ]
      }
    ]
  },
  {
    mainHeader: "Payment Guidelines",
    subList: [{
        subHeader: "Within City and Outstation Orders",
        pointList: [
          {
            point: "The remaining amount should be paid to the Partner at the destination once the order is completed.",
            subPointList: []
          },
          {
            point: "Any Toll charge incurred during the order is not covered in this service, it has to be separately borne by the customer",
            subPointList: []
          }
        ]
      }]
  }
];

export {
  newList ,
}
/* No side effect */
