// Generated by ReScript, PLEASE EDIT WITH CARE


var tncList = [{
    header: /* [] */0,
    subList: {
      bulletType: /* Roman */0,
      arrayList: [
        {
          header: {
            hd: {
              message: "Order Booking Details and Modifications",
              decorationType: /* None */2
            },
            tl: /* [] */0
          },
          subList: {
            bulletType: /* Number */1,
            arrayList: [
              {
                header: {
                  hd: {
                    message: "Quotation and Changes",
                    decorationType: /* None */2
                  },
                  tl: /* [] */0
                },
                subList: {
                  bulletType: /* Disc */2,
                  arrayList: [
                    {
                      header: {
                        hd: {
                          message: "The provided quotation is based on the details provided by the customer, including the movement date, pickup and drop location.",
                          decorationType: /* None */2
                        },
                        tl: /* [] */0
                      },
                      subList: {
                        bulletType: /* None */4,
                        arrayList: []
                      }
                    },
                    {
                      header: {
                        hd: {
                          message: "If there are any deviations in the movement date, or pickup and drop location revising the distance a revised quotation will be offered based on the changes.",
                          decorationType: /* None */2
                        },
                        tl: /* [] */0
                      },
                      subList: {
                        bulletType: /* None */4,
                        arrayList: []
                      }
                    },
                    {
                      header: {
                        hd: {
                          message: "For any issues with respect to the revised quotation, the customer is expected to contact Porter customer care directly at",
                          decorationType: /* None */2
                        },
                        tl: {
                          hd: {
                            message: " 022 4410 4444 / 022 6268 4444.",
                            decorationType: /* Bold */0
                          },
                          tl: /* [] */0
                        }
                      },
                      subList: {
                        bulletType: /* None */4,
                        arrayList: []
                      }
                    }
                  ]
                }
              },
              {
                header: {
                  hd: {
                    message: "Cancellation",
                    decorationType: /* None */2
                  },
                  tl: /* [] */0
                },
                subList: {
                  bulletType: /* Disc */2,
                  arrayList: [
                    {
                      header: {
                        hd: {
                          message: "Free cancellation is allowed up to 1 hour before the scheduled time slot.",
                          decorationType: /* None */2
                        },
                        tl: /* [] */0
                      },
                      subList: {
                        bulletType: /* None */4,
                        arrayList: []
                      }
                    },
                    {
                      header: {
                        hd: {
                          message: "If the cancellation is made after this timeframe, a cancellation fee will be charged.",
                          decorationType: /* None */2
                        },
                        tl: /* [] */0
                      },
                      subList: {
                        bulletType: /* None */4,
                        arrayList: []
                      }
                    }
                  ]
                }
              },
              {
                header: {
                  hd: {
                    message: "Partner Assignment and Details",
                    decorationType: /* None */2
                  },
                  tl: /* [] */0
                },
                subList: {
                  bulletType: /* Disc */2,
                  arrayList: [
                    {
                      header: {
                        hd: {
                          message: "For advance bookings, the partner will be assigned roughly 24 hours before the scheduled time slot.",
                          decorationType: /* None */2
                        },
                        tl: /* [] */0
                      },
                      subList: {
                        bulletType: /* None */4,
                        arrayList: []
                      }
                    },
                    {
                      header: {
                        hd: {
                          message: "The details of the partner will be shared 1 hour prior to the scheduled time slot.",
                          decorationType: /* None */2
                        },
                        tl: /* [] */0
                      },
                      subList: {
                        bulletType: /* None */4,
                        arrayList: []
                      }
                    }
                  ]
                }
              },
              {
                header: {
                  hd: {
                    message: "Price and Taxes",
                    decorationType: /* None */2
                  },
                  tl: /* [] */0
                },
                subList: {
                  bulletType: /* Disc */2,
                  arrayList: [
                    {
                      header: {
                        hd: {
                          message: "The price mentioned in the quotation is inclusive of any applicable taxes excluding any toll charges.",
                          decorationType: /* None */2
                        },
                        tl: /* [] */0
                      },
                      subList: {
                        bulletType: /* None */4,
                        arrayList: []
                      }
                    },
                    {
                      header: {
                        hd: {
                          message: "Please note that the price is subject to change based on slot availability at the time of any modification.",
                          decorationType: /* None */2
                        },
                        tl: /* [] */0
                      },
                      subList: {
                        bulletType: /* None */4,
                        arrayList: []
                      }
                    }
                  ]
                }
              },
              {
                header: {
                  hd: {
                    message: "Warehousing",
                    decorationType: /* None */2
                  },
                  tl: /* [] */0
                },
                subList: {
                  bulletType: /* Disc */2,
                  arrayList: [{
                      header: {
                        hd: {
                          message: "Warehousing facilities can be provided at an additional cost of Rs. 300 per day, subject to availability.",
                          decorationType: /* None */2
                        },
                        tl: /* [] */0
                      },
                      subList: {
                        bulletType: /* None */4,
                        arrayList: []
                      }
                    }]
                }
              },
              {
                header: {
                  hd: {
                    message: "Waiting Charges",
                    decorationType: /* None */2
                  },
                  tl: /* [] */0
                },
                subList: {
                  bulletType: /* Disc */2,
                  arrayList: [
                    {
                      header: {
                        hd: {
                          message: "This service includes 60 minutes of free loading and unloading time.",
                          decorationType: /* None */2
                        },
                        tl: /* [] */0
                      },
                      subList: {
                        bulletType: /* None */4,
                        arrayList: []
                      }
                    },
                    {
                      header: {
                        hd: {
                          message: "Any extra waiting or Loading/Unloading time will be charged extra at Rs. 3/- per minute.",
                          decorationType: /* None */2
                        },
                        tl: /* [] */0
                      },
                      subList: {
                        bulletType: /* None */4,
                        arrayList: []
                      }
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          header: {
            hd: {
              message: "Payment Guidelines",
              decorationType: /* None */2
            },
            tl: /* [] */0
          },
          subList: {
            bulletType: /* Number */1,
            arrayList: [{
                header: {
                  hd: {
                    message: "Within City and Outstation Orders",
                    decorationType: /* None */2
                  },
                  tl: /* [] */0
                },
                subList: {
                  bulletType: /* Disc */2,
                  arrayList: [{
                      header: {
                        hd: {
                          message: "Please ensure that following payment terms are followed to facilitate a smooth and hassle-free experience.",
                          decorationType: /* None */2
                        },
                        tl: /* [] */0
                      },
                      subList: {
                        bulletType: /* Circle */3,
                        arrayList: [
                          {
                            header: {
                              hd: {
                                message: "The remaining amount should be paid to the Partner at the destination once the order is completed.",
                                decorationType: /* None */2
                              },
                              tl: /* [] */0
                            },
                            subList: {
                              bulletType: /* None */4,
                              arrayList: []
                            }
                          },
                          {
                            header: {
                              hd: {
                                message: "Any Toll charge incurred during the order is not covered ",
                                decorationType: /* Orange */1
                              },
                              tl: {
                                hd: {
                                  message: "in this service, it has to be separately borne by the customer",
                                  decorationType: /* None */2
                                },
                                tl: /* [] */0
                              }
                            },
                            subList: {
                              bulletType: /* None */4,
                              arrayList: []
                            }
                          }
                        ]
                      }
                    }]
                }
              }]
          }
        },
        {
          header: {
            hd: {
              message: "Goods and Items details",
              decorationType: /* None */2
            },
            tl: /* [] */0
          },
          subList: {
            bulletType: /* Number */1,
            arrayList: [
              {
                header: {
                  hd: {
                    message: "Restricted Items",
                    decorationType: /* None */2
                  },
                  tl: /* [] */0
                },
                subList: {
                  bulletType: /* Disc */2,
                  arrayList: [
                    {
                      header: {
                        hd: {
                          message: "The following goods are not acceptable for movement: Construction materials, Agricultural Items, jewellery, arms and ammunition, hazardous materials such as crackers, explosives, chemicals, battery acids, inflammable oils (e.g., diesel, petrol, kerosene, gasoline), narcotics, and counterfeit items.",
                          decorationType: /* None */2
                        },
                        tl: /* [] */0
                      },
                      subList: {
                        bulletType: /* None */4,
                        arrayList: []
                      }
                    },
                    {
                      header: {
                        hd: {
                          message: "Heavy items like Sofa, Almirah, Double Cot can’t be moved in this service",
                          decorationType: /* None */2
                        },
                        tl: /* [] */0
                      },
                      subList: {
                        bulletType: /* None */4,
                        arrayList: []
                      }
                    },
                    {
                      header: {
                        hd: {
                          message: "Fragile items like Mirrors, Pots, Glasswares can’t be moved in this service",
                          decorationType: /* None */2
                        },
                        tl: /* [] */0
                      },
                      subList: {
                        bulletType: /* None */4,
                        arrayList: []
                      }
                    },
                    {
                      header: {
                        hd: {
                          message: "Please keep all valuable items like cash and jewelry under your custody before the shifting process begins.",
                          decorationType: /* None */2
                        },
                        tl: /* [] */0
                      },
                      subList: {
                        bulletType: /* None */4,
                        arrayList: []
                      }
                    }
                  ]
                }
              },
              {
                header: {
                  hd: {
                    message: "Technical Assistance",
                    decorationType: /* None */2
                  },
                  tl: /* [] */0
                },
                subList: {
                  bulletType: /* Disc */2,
                  arrayList: [{
                      header: {
                        hd: {
                          message: "If any machines, appliances, or electronic gadgets require the technical assistance of the manufacturer or their authorized dealer for locking/unlocking, it is the customer's responsibility to arrange for this assistance.",
                          decorationType: /* None */2
                        },
                        tl: /* [] */0
                      },
                      subList: {
                        bulletType: /* None */4,
                        arrayList: []
                      }
                    }]
                }
              }
            ]
          }
        },
        {
          header: {
            hd: {
              message: "Other important information",
              decorationType: /* None */2
            },
            tl: /* [] */0
          },
          subList: {
            bulletType: /* Number */1,
            arrayList: [
              {
                header: {
                  hd: {
                    message: "Delays and Restricted Entry",
                    decorationType: /* None */2
                  },
                  tl: /* [] */0
                },
                subList: {
                  bulletType: /* Disc */2,
                  arrayList: [
                    {
                      header: {
                        hd: {
                          message: "Due to No Entry Hours in specific cities, restricted movement, festival days, or peak days, there might be delays in the arrival of the vehicle.",
                          decorationType: /* None */2
                        },
                        tl: /* [] */0
                      },
                      subList: {
                        bulletType: /* None */4,
                        arrayList: []
                      }
                    },
                    {
                      header: {
                        hd: {
                          message: "It is essential to be aware of the timings during which external vehicles are allowed inside the premises. Some societies have shifting restrictions in the morning, evening, or on Sundays. Please check with the society before the shifting date.",
                          decorationType: /* None */2
                        },
                        tl: /* [] */0
                      },
                      subList: {
                        bulletType: /* None */4,
                        arrayList: []
                      }
                    },
                    {
                      header: {
                        hd: {
                          message: "If any permissions are required, the customer should take them in advance from the Resident Welfare Association.",
                          decorationType: /* None */2
                        },
                        tl: /* [] */0
                      },
                      subList: {
                        bulletType: /* None */4,
                        arrayList: []
                      }
                    }
                  ]
                }
              },
              {
                header: {
                  hd: {
                    message: "Disputes and Changes",
                    decorationType: /* None */2
                  },
                  tl: /* [] */0
                },
                subList: {
                  bulletType: /* Disc */2,
                  arrayList: [{
                      header: {
                        hd: {
                          message: "Porter will not entertain disputes regarding aspects that are not included in the quote and were not officially communicated to the Porter Support team when changes were made. It is important to get the quote updated accordingly.",
                          decorationType: /* None */2
                        },
                        tl: /* [] */0
                      },
                      subList: {
                        bulletType: /* None */4,
                        arrayList: []
                      }
                    }]
                }
              },
              {
                header: {
                  hd: {
                    message: "Rope Pulling Requirements",
                    decorationType: /* None */2
                  },
                  tl: /* [] */0
                },
                subList: {
                  bulletType: /* Disc */2,
                  arrayList: [{
                      header: {
                        hd: {
                          message: "This service does not include item movement via Rope Pulling, Customer will have to arrange for it separately.",
                          decorationType: /* None */2
                        },
                        tl: /* [] */0
                      },
                      subList: {
                        bulletType: /* None */4,
                        arrayList: []
                      }
                    }]
                }
              }
            ]
          }
        }
      ]
    }
  }];

var newList3 = [
  {
    header: {
      hd: {
        message: "Order Booking Details and Modifications",
        decorationType: /* None */2
      },
      tl: /* [] */0
    },
    bulletType: /* Roman */0,
    subList: [
      {
        header: {
          hd: {
            message: "Quotation and Changes",
            decorationType: /* None */2
          },
          tl: /* [] */0
        },
        bulletType: /* Number */1,
        subList: [
          {
            header: {
              hd: {
                message: "The provided quotation is based on the details provided by the customer, including the movement date, pickup and drop location.",
                decorationType: /* None */2
              },
              tl: /* [] */0
            },
            bulletType: /* Disc */2,
            subList: []
          },
          {
            header: {
              hd: {
                message: "If there are any deviations in the movement date, or pickup and drop location revising the distance a revised quotation will be offered based on the changes.",
                decorationType: /* None */2
              },
              tl: /* [] */0
            },
            bulletType: /* Disc */2,
            subList: []
          },
          {
            header: {
              hd: {
                message: "For any issues with respect to the revised quotation, the customer is expected to contact Porter customer care directly at",
                decorationType: /* None */2
              },
              tl: {
                hd: {
                  message: " 022 4410 4444 / 022 6268 4444.",
                  decorationType: /* Bold */0
                },
                tl: /* [] */0
              }
            },
            bulletType: /* Disc */2,
            subList: []
          }
        ]
      },
      {
        header: {
          hd: {
            message: "Cancellation",
            decorationType: /* None */2
          },
          tl: /* [] */0
        },
        bulletType: /* Number */1,
        subList: [
          {
            header: {
              hd: {
                message: "Free cancellation is allowed up to 1 hour before the scheduled time slot.",
                decorationType: /* None */2
              },
              tl: /* [] */0
            },
            bulletType: /* Disc */2,
            subList: []
          },
          {
            header: {
              hd: {
                message: "If the cancellation is made after this timeframe, a cancellation fee will be charged.",
                decorationType: /* None */2
              },
              tl: /* [] */0
            },
            bulletType: /* Disc */2,
            subList: []
          }
        ]
      },
      {
        header: {
          hd: {
            message: "Partner Assignment and Details",
            decorationType: /* None */2
          },
          tl: /* [] */0
        },
        bulletType: /* Number */1,
        subList: [
          {
            header: {
              hd: {
                message: "For advance bookings, the partner will be assigned roughly 24 hours before the scheduled time slot.",
                decorationType: /* None */2
              },
              tl: /* [] */0
            },
            bulletType: /* Disc */2,
            subList: []
          },
          {
            header: {
              hd: {
                message: "The details of the partner will be shared 1 hour prior to the scheduled time slot.",
                decorationType: /* None */2
              },
              tl: /* [] */0
            },
            bulletType: /* Disc */2,
            subList: []
          }
        ]
      },
      {
        header: {
          hd: {
            message: "Price and Taxes",
            decorationType: /* None */2
          },
          tl: /* [] */0
        },
        bulletType: /* Number */1,
        subList: [
          {
            header: {
              hd: {
                message: "The price mentioned in the quotation is inclusive of any applicable taxes excluding any toll charges.",
                decorationType: /* None */2
              },
              tl: /* [] */0
            },
            bulletType: /* Disc */2,
            subList: []
          },
          {
            header: {
              hd: {
                message: "Please note that the price is subject to change based on slot availability at the time of any modification.",
                decorationType: /* None */2
              },
              tl: /* [] */0
            },
            bulletType: /* Disc */2,
            subList: []
          }
        ]
      },
      {
        header: {
          hd: {
            message: "Warehousing",
            decorationType: /* None */2
          },
          tl: /* [] */0
        },
        bulletType: /* Number */1,
        subList: [{
            header: {
              hd: {
                message: "Warehousing facilities can be provided at an additional cost of Rs. 300 per day, subject to availability.",
                decorationType: /* None */2
              },
              tl: /* [] */0
            },
            bulletType: /* Disc */2,
            subList: []
          }]
      },
      {
        header: {
          hd: {
            message: "Waiting Charges",
            decorationType: /* None */2
          },
          tl: /* [] */0
        },
        bulletType: /* Number */1,
        subList: [
          {
            header: {
              hd: {
                message: "This service includes 60 minutes of free loading and unloading time.",
                decorationType: /* None */2
              },
              tl: /* [] */0
            },
            bulletType: /* Disc */2,
            subList: []
          },
          {
            header: {
              hd: {
                message: "Any extra waiting or Loading/Unloading time will be charged extra at Rs. 3/- per minute.",
                decorationType: /* None */2
              },
              tl: /* [] */0
            },
            bulletType: /* Disc */2,
            subList: []
          }
        ]
      }
    ]
  },
  {
    header: {
      hd: {
        message: "Payment Guidelines",
        decorationType: /* None */2
      },
      tl: /* [] */0
    },
    bulletType: /* Roman */0,
    subList: [{
        header: {
          hd: {
            message: "Within City and Outstation Orders",
            decorationType: /* None */2
          },
          tl: /* [] */0
        },
        bulletType: /* Number */1,
        subList: [{
            header: {
              hd: {
                message: "Please ensure that following payment terms are followed to facilitate a smooth and hassle-free experience.",
                decorationType: /* None */2
              },
              tl: /* [] */0
            },
            bulletType: /* Disc */2,
            subList: [
              {
                header: {
                  hd: {
                    message: "The remaining amount should be paid to the Partner at the destination once the order is completed.",
                    decorationType: /* None */2
                  },
                  tl: /* [] */0
                },
                bulletType: /* Circle */3,
                subList: []
              },
              {
                header: {
                  hd: {
                    message: "Any Toll charge incurred during the order is not covered ",
                    decorationType: /* Orange */1
                  },
                  tl: {
                    hd: {
                      message: "in this service, it has to be separately borne by the customer",
                      decorationType: /* None */2
                    },
                    tl: /* [] */0
                  }
                },
                bulletType: /* Circle */3,
                subList: []
              }
            ]
          }]
      }]
  },
  {
    header: {
      hd: {
        message: "Goods and Items details",
        decorationType: /* None */2
      },
      tl: /* [] */0
    },
    bulletType: /* Roman */0,
    subList: [
      {
        header: {
          hd: {
            message: "Restricted Items",
            decorationType: /* None */2
          },
          tl: /* [] */0
        },
        bulletType: /* Number */1,
        subList: [
          {
            header: {
              hd: {
                message: "The following goods are not acceptable for movement: Construction materials, Agricultural Items, jewellery, arms and ammunition, hazardous materials such as crackers, explosives, chemicals, battery acids, inflammable oils (e.g., diesel, petrol, kerosene, gasoline), narcotics, and counterfeit items.",
                decorationType: /* None */2
              },
              tl: /* [] */0
            },
            bulletType: /* Disc */2,
            subList: []
          },
          {
            header: {
              hd: {
                message: "Heavy items like Sofa, Almirah, Double Cot can’t be moved in this service",
                decorationType: /* None */2
              },
              tl: /* [] */0
            },
            bulletType: /* Disc */2,
            subList: []
          },
          {
            header: {
              hd: {
                message: "Fragile items like Mirrors, Pots, Glasswares can’t be moved in this service",
                decorationType: /* None */2
              },
              tl: /* [] */0
            },
            bulletType: /* Disc */2,
            subList: []
          },
          {
            header: {
              hd: {
                message: "Please keep all valuable items like cash and jewelry under your custody before the shifting process begins.",
                decorationType: /* None */2
              },
              tl: /* [] */0
            },
            bulletType: /* Disc */2,
            subList: []
          }
        ]
      },
      {
        header: {
          hd: {
            message: "Technical Assistance",
            decorationType: /* None */2
          },
          tl: /* [] */0
        },
        bulletType: /* Number */1,
        subList: [{
            header: {
              hd: {
                message: "If any machines, appliances, or electronic gadgets require the technical assistance of the manufacturer or their authorized dealer for locking/unlocking, it is the customer's responsibility to arrange for this assistance.",
                decorationType: /* None */2
              },
              tl: /* [] */0
            },
            bulletType: /* Disc */2,
            subList: []
          }]
      }
    ]
  },
  {
    header: {
      hd: {
        message: "Other important information",
        decorationType: /* None */2
      },
      tl: /* [] */0
    },
    bulletType: /* Roman */0,
    subList: [
      {
        header: {
          hd: {
            message: "Delays and Restricted Entry",
            decorationType: /* None */2
          },
          tl: /* [] */0
        },
        bulletType: /* Number */1,
        subList: [
          {
            header: {
              hd: {
                message: "Due to No Entry Hours in specific cities, restricted movement, festival days, or peak days, there might be delays in the arrival of the vehicle.",
                decorationType: /* None */2
              },
              tl: /* [] */0
            },
            bulletType: /* Disc */2,
            subList: []
          },
          {
            header: {
              hd: {
                message: "It is essential to be aware of the timings during which external vehicles are allowed inside the premises. Some societies have shifting restrictions in the morning, evening, or on Sundays. Please check with the society before the shifting date.",
                decorationType: /* None */2
              },
              tl: /* [] */0
            },
            bulletType: /* Disc */2,
            subList: []
          },
          {
            header: {
              hd: {
                message: "If any permissions are required, the customer should take them in advance from the Resident Welfare Association.",
                decorationType: /* None */2
              },
              tl: /* [] */0
            },
            bulletType: /* Disc */2,
            subList: []
          }
        ]
      },
      {
        header: {
          hd: {
            message: "Disputes and Changes",
            decorationType: /* None */2
          },
          tl: /* [] */0
        },
        bulletType: /* Number */1,
        subList: [{
            header: {
              hd: {
                message: "Porter will not entertain disputes regarding aspects that are not included in the quote and were not officially communicated to the Porter Support team when changes were made. It is important to get the quote updated accordingly.",
                decorationType: /* None */2
              },
              tl: /* [] */0
            },
            bulletType: /* Disc */2,
            subList: []
          }]
      },
      {
        header: {
          hd: {
            message: "Rope Pulling Requirements",
            decorationType: /* None */2
          },
          tl: /* [] */0
        },
        bulletType: /* Number */1,
        subList: [{
            header: {
              hd: {
                message: "This service does not include item movement via Rope Pulling, Customer will have to arrange for it separately.",
                decorationType: /* None */2
              },
              tl: /* [] */0
            },
            bulletType: /* Disc */2,
            subList: []
          }]
      }
    ]
  }
];

var newList = [
  {
    mainHeader: "Order Booking Details and Modifications",
    subList: [
      {
        subHeader: "Quotation and Changes:",
        pointList: [
          {
            point: "The provided quotation is based on the details provided by the customer, including the movement date, pickup and drop location.",
            subPointList: []
          },
          {
            point: "If there are any deviations in the movement date, or pickup and drop location revising the distance a revised quotation will be offered based on the changes.",
            subPointList: []
          },
          {
            point: "For any issues with respect to the revised quotation, the customer is expected to contact Porter customer care directly at 022 4410 4444 / 022 6268 4444.",
            subPointList: []
          }
        ]
      },
      {
        subHeader: "Cancellation",
        pointList: [
          {
            point: "Free cancellation is allowed up to 1 hour before the scheduled time slot",
            subPointList: [
              "test",
              "test2"
            ]
          },
          {
            point: "If the cancellation is made after this timeframe, a cancellation fee will be charged.",
            subPointList: []
          }
        ]
      }
    ]
  },
  {
    mainHeader: "Payment Guidelines",
    subList: [{
        subHeader: "Within City and Outstation Orders",
        pointList: [
          {
            point: "The remaining amount should be paid to the Partner at the destination once the order is completed.",
            subPointList: []
          },
          {
            point: "Any Toll charge incurred during the order is not covered in this service, it has to be separately borne by the customer",
            subPointList: []
          }
        ]
      }]
  }
];

export {
  tncList ,
  newList3 ,
  newList ,
}
/* No side effect */
