// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Footer(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                "Feel free to contact Porter customer care at ",
                JsxRuntime.jsx("span", {
                      children: "022 4410 4444 / 022 6268 4444 ",
                      className: "bold"
                    }),
                "or mail us at ",
                JsxRuntime.jsx("span", {
                      children: "packermover@porter.in ",
                      className: "bold"
                    }),
                "for any further assistance."
              ],
              className: "footer"
            });
}

var make = Footer;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
