// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CloseIcon from "./CloseIcon.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as CloseIconSvg from "./assets/svg/close-icon.svg";

var closeIcon = CloseIconSvg;

function Header(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("p", {
                      children: "Terms & conditions"
                    }),
                JsxRuntime.jsx(CloseIcon.make, {})
              ],
              className: "tnc-header"
            });
}

var make = Header;

export {
  closeIcon ,
  make ,
}
/* closeIcon Not a pure module */
