// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function tncRec(data) {
  var printPoint = function (item) {
    return Belt_Array.mapWithIndex(Belt_List.toArray(item.header), (function (i, subArrayItem) {
                  var match = subArrayItem.decorationType;
                  switch (match) {
                    case /* Bold */0 :
                        return JsxRuntime.jsx("span", {
                                    children: subArrayItem.message,
                                    className: "bold"
                                  });
                    case /* Orange */1 :
                        return JsxRuntime.jsx("span", {
                                    children: subArrayItem.message,
                                    className: "orange"
                                  });
                    case /* None */2 :
                        return subArrayItem.message;
                    
                  }
                }));
  };
  return Belt_Array.mapWithIndex(data, (function (ind, item) {
                var match = item.bulletType;
                switch (match) {
                  case /* Roman */0 :
                      return JsxRuntime.jsxs(JsxRuntime.Fragment, {
                                  children: [
                                    JsxRuntime.jsx("li", {
                                          children: printPoint(item)
                                        }, String(ind)),
                                    JsxRuntime.jsx("ol", {
                                          children: tncRec(item.subList),
                                          type: "I"
                                        })
                                  ]
                                });
                  case /* Number */1 :
                      return JsxRuntime.jsxs("ol", {
                                  children: [
                                    JsxRuntime.jsx("li", {
                                          children: printPoint(item)
                                        }, String(ind)),
                                    tncRec(item.subList)
                                  ],
                                  type: "1"
                                });
                  case /* Disc */2 :
                      return JsxRuntime.jsxs("ul", {
                                  children: [
                                    JsxRuntime.jsx("li", {
                                          children: printPoint(item)
                                        }, String(ind)),
                                    tncRec(item.subList)
                                  ],
                                  className: "disc-dot-dark"
                                });
                  case /* Circle */3 :
                      return JsxRuntime.jsxs("ul", {
                                  children: [
                                    JsxRuntime.jsx("li", {
                                          children: printPoint(item)
                                        }, String(ind)),
                                    tncRec(item.subList)
                                  ],
                                  className: "circle-dot-light"
                                });
                  case /* None */4 :
                      throw {
                            RE_EXN_ID: "Match_failure",
                            _1: [
                              "TermsAndConditionContent.res",
                              64,
                              4
                            ],
                            Error: new Error()
                          };
                  
                }
              }));
}

function TermsAndConditionContent(props) {
  return JsxRuntime.jsx("div", {
              children: tncRec(props.data)
            });
}

var make = TermsAndConditionContent;

export {
  tncRec ,
  make ,
}
/* react/jsx-runtime Not a pure module */
