// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function tncRec(data) {
  var printPoint = function (item) {
    return Belt_Array.map(Belt_List.toArray(item.header), (function (subArrayItem) {
                  var match = subArrayItem.decorationType;
                  switch (match) {
                    case /* Bold */0 :
                        return JsxRuntime.jsx("span", {
                                    children: subArrayItem.message,
                                    className: "bold"
                                  }, subArrayItem.message);
                    case /* Orange */1 :
                        return JsxRuntime.jsx("span", {
                                    children: subArrayItem.message,
                                    className: "orange"
                                  }, subArrayItem.message);
                    case /* None */2 :
                        return JsxRuntime.jsx(React.Fragment, {
                                    children: subArrayItem.message
                                  }, subArrayItem.message);
                    
                  }
                }));
  };
  return Belt_Array.mapWithIndex(data, (function (ind, item) {
                var match = item.subList.bulletType;
                switch (match) {
                  case /* Roman */0 :
                      return JsxRuntime.jsx(React.Fragment, {
                                  children: JsxRuntime.jsx("ol", {
                                        children: tncRec(item.subList.arrayList),
                                        type: "I"
                                      })
                                }, String(ind));
                  case /* Number */1 :
                      return JsxRuntime.jsxs(React.Fragment, {
                                  children: [
                                    JsxRuntime.jsx("li", {
                                          children: printPoint(item),
                                          className: "point-header"
                                        }),
                                    JsxRuntime.jsx("ol", {
                                          children: tncRec(item.subList.arrayList),
                                          type: "1"
                                        })
                                  ]
                                }, String(ind));
                  case /* Disc */2 :
                      return JsxRuntime.jsxs(React.Fragment, {
                                  children: [
                                    JsxRuntime.jsx("li", {
                                          children: printPoint(item),
                                          className: "point-header"
                                        }),
                                    JsxRuntime.jsx("ul", {
                                          children: tncRec(item.subList.arrayList),
                                          className: "disc-dot-dark"
                                        })
                                  ]
                                }, String(ind));
                  case /* Circle */3 :
                      return JsxRuntime.jsxs(React.Fragment, {
                                  children: [
                                    JsxRuntime.jsx("li", {
                                          children: printPoint(item),
                                          className: "normal-point"
                                        }),
                                    JsxRuntime.jsx("ul", {
                                          children: tncRec(item.subList.arrayList),
                                          className: "circle-dot-light"
                                        })
                                  ]
                                }, String(ind));
                  case /* None */4 :
                      return JsxRuntime.jsx("li", {
                                  children: printPoint(item),
                                  className: "normal-point"
                                }, String(ind));
                  
                }
              }));
}

function TermsAndConditionList(props) {
  return JsxRuntime.jsx("div", {
              children: tncRec(props.data)
            });
}

var make = TermsAndConditionList;

export {
  tncRec ,
  make ,
}
/* react Not a pure module */
